name: HTML Check

on:
  push:
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: .
        log_level: DEBUG
