name: HTML Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action
      with:
       root: git-workflow/
        blacklist: invalid






