name: HTML Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: DavidRV12/git-workflow/index.html
        log_level: DEBUG

